summary: |
  This earthquake example demonstrates rapid analysis capabilities with the HAZUS earthquake damage and loss assessment methodology. Building-level Damage and Losses (D&L) are calculated directly from Intensity Measures (IM) for 100 assets. The IM field that represents peak ground acceleration in the city of San Francisco, CA, from an Mw7.2 event on the San Andreas fault, was obtained from Probabilistic Seismic Hazard Analysis (PSHA).

#<p>Tags: (IM field from PSHA | IM as EDP | HAZUS building-level D&L)<p>

#[150k buildings in the full inventory with 100 selected for analysis]

difficulty: 1

